# Generated by Django 6.0.7 on 2026-08-03 13:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "suit",
                    models.CharField(
                        choices=[("H", "Coeur"), ("D", "Carreau"), ("C", "Trefle"), ("S", "Pique")],
                        max_length=1,
                    ),
                ),
                (
                    "rank",
                    models.CharField(
                        choices=[
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                            ("J", "Valet"),
                            ("Q", "Dame"),
                            ("K", "Roi"),
                            ("A", "As"),
                        ],
                        max_length=2,
                    ),
                ),
            ],
            options={
                "ordering": ["suit", "rank"],
                "indexes": [
                    models.Index(fields=["suit", "rank"], name="blackjack_c_suit_73c3e0_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("suit", "rank"), name="unique_suit_rank")
                ],
            },
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(editable=False, max_length=8, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente"),
                            ("EN_COURS", "En cours"),
                            ("TERMINEE", "Terminee"),
                        ],
                        default="EN_ATTENTE",
                        max_length=12,
                    ),
                ),
                (
                    "max_players",
                    models.PositiveSmallIntegerField(
                        default=3, validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("current_turn_seat", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("dealer_hand", models.JSONField(default=list)),
                ("dealer_revealed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosted_games",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Deck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("cards_remaining", models.JSONField(default=list)),
                ("discard_pile", models.JSONField(default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deck",
                        to="blackjack.game",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MoveLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("DEAL", "Distribution"),
                            ("HIT", "Tirer"),
                            ("STAND", "Rester"),
                            ("DOUBLE", "Doubler"),
                            ("BUST", "Depasse"),
                            ("BLACKJACK", "Blackjack"),
                            ("DEALER_HIT", "Tirage croupier"),
                            ("DEALER_STAND", "Croupier reste"),
                            ("ROUND_END", "Fin de manche"),
                        ],
                        max_length=12,
                    ),
                ),
                ("card", models.CharField(blank=True, max_length=3)),
                ("hand_total", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moves",
                        to="blackjack.game",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moves",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Participation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("seat", models.PositiveSmallIntegerField()),
                ("hand", models.JSONField(default=list)),
                ("bet", models.PositiveIntegerField(default=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WAITING", "En attente"),
                            ("PLAYING", "En jeu"),
                            ("STOOD", "Reste"),
                            ("BUST", "Depasse"),
                            ("BLACKJACK", "Blackjack"),
                            ("LEFT", "Parti"),
                        ],
                        default="WAITING",
                        max_length=12,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("WIN", "Gagne"),
                            ("LOSE", "Perdu"),
                            ("PUSH", "Egalite"),
                            ("BLACKJACK", "Blackjack"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to="blackjack.game",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["seat"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("chips", models.PositiveIntegerField(default=1000)),
                ("games_played", models.PositiveIntegerField(default=0)),
                ("games_won", models.PositiveIntegerField(default=0)),
                ("games_lost", models.PositiveIntegerField(default=0)),
                ("games_pushed", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(fields=["status"], name="blackjack_g_status_fa6c51_idx"),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(fields=["created_at"], name="blackjack_g_created_6ee52c_idx"),
        ),
        migrations.AddIndex(
            model_name="movelog",
            index=models.Index(
                fields=["game", "created_at"], name="blackjack_m_game_id_d9739a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="participation",
            index=models.Index(fields=["game", "status"], name="blackjack_p_game_id_60f402_idx"),
        ),
        migrations.AddConstraint(
            model_name="participation",
            constraint=models.UniqueConstraint(
                fields=("game", "player"), name="unique_player_per_game"
            ),
        ),
        migrations.AddConstraint(
            model_name="participation",
            constraint=models.UniqueConstraint(
                fields=("game", "seat"), name="unique_seat_per_game"
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(fields=["user"], name="blackjack_p_user_id_21aeb8_idx"),
        ),
    ]
